# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trader_designer.ui'
#
# Created: Tue Sep 17 22:26:37 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(802, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabBuySell = QtGui.QWidget()
        self.tabBuySell.setObjectName(_fromUtf8("tabBuySell"))
        self.tabWidget.addTab(self.tabBuySell, _fromUtf8(""))
        self.tabAPI = QtGui.QWidget()
        self.tabAPI.setObjectName(_fromUtf8("tabAPI"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabAPI)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.toolButton_Delete = QtGui.QToolButton(self.tabAPI)
        self.toolButton_Delete.setMinimumSize(QtCore.QSize(25, 23))
        self.toolButton_Delete.setObjectName(_fromUtf8("toolButton_Delete"))
        self.gridLayout_2.addWidget(self.toolButton_Delete, 0, 1, 1, 1)
        self.toolButton_New = QtGui.QToolButton(self.tabAPI)
        self.toolButton_New.setMinimumSize(QtCore.QSize(25, 23))
        self.toolButton_New.setObjectName(_fromUtf8("toolButton_New"))
        self.gridLayout_2.addWidget(self.toolButton_New, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.tableWidget_APIs = QtGui.QTableWidget(self.tabAPI)
        self.tableWidget_APIs.setObjectName(_fromUtf8("tableWidget_APIs"))
        self.tableWidget_APIs.setColumnCount(6)
        self.tableWidget_APIs.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_APIs.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_APIs.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_APIs.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_APIs.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_APIs.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_APIs.setHorizontalHeaderItem(5, item)
        self.tableWidget_APIs.verticalHeader().setMinimumSectionSize(100)
        self.gridLayout_2.addWidget(self.tableWidget_APIs, 1, 0, 1, 5)
        self.toolButtonLoadAPIs = QtGui.QToolButton(self.tabAPI)
        self.toolButtonLoadAPIs.setMinimumSize(QtCore.QSize(0, 23))
        self.toolButtonLoadAPIs.setObjectName(_fromUtf8("toolButtonLoadAPIs"))
        self.gridLayout_2.addWidget(self.toolButtonLoadAPIs, 0, 2, 1, 1)
        self.toolButtonSaveAPIs = QtGui.QToolButton(self.tabAPI)
        self.toolButtonSaveAPIs.setMinimumSize(QtCore.QSize(0, 23))
        self.toolButtonSaveAPIs.setObjectName(_fromUtf8("toolButtonSaveAPIs"))
        self.gridLayout_2.addWidget(self.toolButtonSaveAPIs, 0, 3, 1, 1)
        self.tabWidget.addTab(self.tabAPI, _fromUtf8(""))
        self.tab_bots = QtGui.QWidget()
        self.tab_bots.setObjectName(_fromUtf8("tab_bots"))
        self.tabWidget.addTab(self.tab_bots, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 2)
        self.treeWidgetValues = QtGui.QTreeWidget(self.centralwidget)
        self.treeWidgetValues.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeWidgetValues.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.treeWidgetValues.setObjectName(_fromUtf8("treeWidgetValues"))
        self.gridLayout.addWidget(self.treeWidgetValues, 0, 1, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_mpl = QtGui.QGridLayout(self.frame)
        self.gridLayout_mpl.setMargin(0)
        self.gridLayout_mpl.setSpacing(0)
        self.gridLayout_mpl.setObjectName(_fromUtf8("gridLayout_mpl"))
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionABout = QtGui.QAction(MainWindow)
        self.actionABout.setObjectName(_fromUtf8("actionABout"))
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionABout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBuySell), QtGui.QApplication.translate("MainWindow", "Buy/Sell", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_Delete.setToolTip(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_Delete.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_New.setToolTip(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_New.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_APIs.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Market", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_APIs.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Key", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_APIs.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Secret/Sign", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_APIs.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Sample Rate [s]", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_APIs.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Last Poll", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_APIs.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonLoadAPIs.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonSaveAPIs.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAPI), QtGui.QApplication.translate("MainWindow", "API Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bots), QtGui.QApplication.translate("MainWindow", "Bots", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetValues.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetValues.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetValues.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "line", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionABout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

